name: API Testing Workflow

on: [push, pull_request]

jobs:
  test-api:
    runs-on: ubuntu-22.04

    steps:
    # Checkout code
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    # Install dependencies
    - name: Install dependencies
      run: npm install

    # Test API Endpoints
    - name: Test API
      run: |
        node <<EOF
        const fetch = require('node-fetch');

        async function testAPI() {
          const response = await fetch('https://example.com/api', { method: 'GET' });
          if (response.ok) {
            console.log('API GET request passed!');
          } else {
            throw new Error('API GET request failed');
          }

          const postResponse = await fetch('https://example.com/api', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ data: 'test' })
          });

          if (postResponse.ok) {
            console.log('API POST request passed!');
          } else {
            throw new Error('API POST request failed');
          }
        }

        testAPI().catch(err => {
          console.error(err);
          process.exit(1);
        });
        EOF
